server:
  port: 8088

spring:
  appllication:
    name:SpringBoot_week03-prod

app:
  app-name: 企业后台管理系统
  version: 1.0.3
  description: 基于 Spring Boot 3.5.11 for development
  author:
    name: yzx
    email: 2411396953@qq.com
  features:
    - Built with Spring Boot 3.5.11
    - Production profile enabled
    - Integrated Spring Security
    - Integrated Spring Data Redis
  published: true